### ISSUE TITLE
habitat.all() returns unparsed values

### ISSUE THREAD

**Issue by k88hudson** [brianloveswords/habitat#13]
Not sure if this intended, but `all()` returns `process.env` without being parsed.
(See https://github.com/brianloveswords/habitat/blob/master/index.js#L161)

i.e. for 

```
SOMETHING=false
```

`habitat.get('SOMETHING')` is `false` but `habitat.all().SOMETHING` is truthy.

I would expect it to return parsed values, what do you think?

**Comment by brianloveswords** [comment]
As we discussed on IRC, I think you're right, but we should leave the old behavior behind a flag, something like

``` js
habitat.all({raw: true})
```
