### ISSUE TITLE
Only top-level keys in the defaults object can be directly referenced

### ISSUE THREAD

**Issue by eetuhuisman** [brianloveswords/habitat#15]
Not sure if it is by design or not, but getting a value with its full path for a key which is set in an object inside the `defaults` object always returns `undefined`.

``` javascript
var habitat = require('habitat');
var env = new habitat('app', {
    prefix: {
        key: 'value'
    }
});

require('assert').strictEqual(env.get('prefixKey'), env.get('prefix').key);
// AssertionError: "undefined" === "value"
```

Fixing this would make the `defaults` somewhat more useful as I wouldn't have to worry about where the value is coming from.

**Comment by brianloveswords** [comment]
Definitely not by design, more of an oversight. If you feel like taking a crack at this, I'm happy to accept PRs, otherwise I'll try to get to it soon!
