### ISSUE TITLE
remove lodash foreach/reduce?

### ISSUE THREAD

**Issue by Pomax** [brianloveswords/habitat#20]
A look at the code suggests that the lodash reduce and foreach are used extremely sparsely, making it worth not having the lodash dependency at all (especially since lodash creates extremely deep paths, causing problems on windows)

**Comment by brianloveswords** [comment]
Send in a PR, happy to remove 'em!

**Comment by Pomax** [comment]
cool, I'll see how far I get (also messing about with rewriting several things to React atm, so it might be a few days)

**Comment by brianloveswords** [comment]
I just did it myself, check out #21 and see if that looks good to you.

**Comment by jdalton** [comment]
Just a heads up. [lodash v3](https://github.com/lodash/lodash/releases/tag/3.0.0) has significantly reduced the dep graphs of its modularized packages. Also there is now an option of cherry-picking modules from lodash, `require('lodash/array/chunk')` which browserifies/webpacks nicely.
