### ISSUE TITLE
getting a specific prefixed value returns an object

### ISSUE THREAD

**Issue by Pomax** [brianloveswords/habitat#3]
I was using `new Habitat()` with an .env file containing:

```
S3_BUCKET=...
S3_HOSTNAME=...
S3_KEY=...
```

and grabbing `env.get("S3_BUCKET")` returned an object `{ 's3_bucket' : '...' }` rather than merely the string that variable pointed to.

Not sure if this is because of the prefixing, and I don't quite have time to work out a minimal test that shows this happening (need to add in actual S3 faking before I can), but once I'm done with that I'll try to reduce and tack a minimal working example to this report.

**Comment by jbuck** [comment]
@Pomax I wrote a test that does what you describe but it appears to work fine. Can you add more detail (he says, asking more than 1 year later) or close this issue if you cannot?

**Comment by brianloveswords** [comment]
haha oh man, I never even saw this.

**Comment by jbuck** [comment]
@Pomax says to kill this issue

**Comment by Pomax** [comment]
bam
