### ISSUE TITLE
Loading in multiple files

### ISSUE THREAD

**Issue by ScottDowne** [brianloveswords/habitat#6]
Was wondering if there is interest in have multiple env files being supported, like, an .env and .env.defaults

I'm willing to write the patch :)

Just wanted to see if there is:
a. interest
b. ideas or suggestions on what the API to do this would look like

My use case is having an env file that works out of the box checked into an apps repo.

From here, a user could override some of these envs as a new file that git would ignore.

Right now we have env.dist full of defaults checked into the repo, and .env on git ignore. We then ask every user to copy env.dist to .env.

Would be nice if it just worked.

Thoughts?

**Comment by ScottDowne** [comment]
https://github.com/brianloveswords/habitat/pull/7

Review?

**Comment by jbuck** [comment]
Here's how I propose this works: Habitat should first load from process.env, then `n` files called by `Habitat.load()`. As an example, lets say you have the following defined:

```
process.env:
  a=env

local.env:
  a=local
  b=local

defaults.env:
  a=defaults
  b=defaults
  c=defaults
```

You'd end up with the following configuration if you called env.all():

``` js
{
  "a": "env",
  "b": "local",
  "c": "defaults"
}
```
